liqd/zt-app

- theme/colors.js
- theme/fonts.js
- theme/spacings.js
Added FONTS, COLORS and SPACINGS (based on values of adhocracy+)
Initial setup. To be extended modified
> styles/constants: adding constants/libs to use them for styling later:

- containers/Ideas/IdeaCreate.js
- containers/Ideas/IdeasPage.js
- containers/Ideas/IdeasPage.styles.js
- navigation/IdeaNavigator.js
So, I think, this is sth. we can merge and then you can add the actual form @phillimorland !
> ideas: add navigation to idea form

- BaseApi.js
- containers/Ideas/IdeasPage.js
I already added a method for post requests and an example for adding a live question, because it doesnt need authentification, see usage in comments
> Ks 2021 05 add central api

- BaseApi.js
- containers/Auth/LoginScreen.js
- containers/Auth/StartUpScreen.js
- containers/Ideas/IdeaCreate.js
- navigation/IdeaNavigator.js
- package.json
There is now a login screen, but once you logged in with a valid account on aplus dev, it should store the token an no more login is required..
> Ks 2021 06 add login screen

- components/formFields.js
- components/formFields.styles.js
- containers/Ideas/IdeaCreate.js
- package.json
> adding image picker from expo - initial step - limited styling, refactor needed

- .eslintrc.json
- BaseApi.js
- components/formFields.js
- package.json
-Adding command in package.json to run linting and fixing 'npm run lintfix'
-Adding rules: no two or more empty lines and if statements in stroustrup manner
> config/eslint: add command for automatic lint fix

- App.js
- containers/Auth/AuthProvider.js
- containers/Auth/LoginScreen.js
- containers/Auth/StartUpScreen.js
- containers/Ideas/ExplorePage.js
- containers/Ideas/Idea.js
- containers/Ideas/IdeaProject.js
- navigation/IdeaNavigator.js
- package.json
Upgrade to the latest stable version of react-navigation and adjust to the api changes. I had to change the authentication and navigation flow because the switch-navigator has been deprecated.
> jd 2021 06 upgrade to react-navigation 5

- BaseApi.js
- containers/Auth/LoginScreen.js
- containers/Ideas/ExploreListItem.js
- containers/Ideas/ExplorePage.js
- containers/Ideas/IdeaCreate.js
- containers/Ideas/IdeaProject.js
Only posts name and description of ideas.
> Ks 2021 06 post idea

- containers/Ideas/IdeaProject.js
Sorry, forgot to save and commit that.. just to be consistent in naming with projectsListener.
> Ideas/IdeaProject: rename listener

- .github/workflows/react.yml
- README.md
- components/imageFormField.js
Add ci config and auto publish to dev channel
> add github actions ci

- README.md
Because I had troubles finding that again, this might be useful?
> README: add link to emulator setup

- containers/Ideas/IdeaCreate.js
@khamui Here's the stuff we tried!
> containers/ideas: use labels and categories from module

- components/Modal.js
- components/Modal.styles.js
- components/ModalItem.js
- components/ModalItem.styles.js
- containers/Ideas/Idea.js
I am not sure about the reusabilty and the whole approach. But I thought any modal would have a text, an action and a cancel-thing? And if we get something else to cover, we can still change it.
Also unsure about the styling and if I would change the text-size or rather not?
I couldn't get the two lines of text centered on their own, though.
> components/modal: add modal, style and use as deleteModal for idea

- BaseApi.js
- containers/Comments/Comment.js
- containers/Comments/Comment.styles.js
- containers/Comments/Comments.js
- containers/Comments/SubComment.js
- containers/Comments/SubComments.js
- containers/Ideas/Idea.js
I think i created way too many tasks in taiga, which are not part of this story.
What to expect is:
- click on bubble icon in `Idea (Detail)` shows comments
- in case no comments for that particular idea, the bubble icon is disabled
- sub comments is shown, when clicking on `Show x answers`
What is missing:
- Showing the authors avatar
- Functionality of commenting
- Functionality of sharing
- All actions on a (sub-)comment --> edit, delete, report
If something with this task is blocking you, call me or message me, no worries i am available and happy to help unblock.
> app/comments: component layouting and basic functionality

- components/formFields.js
- containers/Ideas/IdeaCreate.js
Finally ... only works with https://github.com/liqd/adhocracy-plus/pull/1394
> Ks 2021 08 post category and labels

- BaseApi.js
- containers/Ideas/Idea.js
- containers/Ideas/IdeaProject.js
- containers/Ideas/IdeasList.js
- containers/Ideas/IdeasListItem.js
depending on: https://github.com/liqd/adhocracy-plus/pull/1395
No error handling so far, but should be ok as button only shown when deletion allowed.
> containers/ideas: delete idea

- components/ButtonCounter.js
- components/ButtonCounter.styles.js
- containers/Ideas/Idea.js
- theme/fonts.js
- more robust on click rage
- equivalent vote numbers of detail and list item
- bugfix: increment/decrement instead of fixed values of 0 and 1
> app/voting: fix voting logic & highlight user vote

- BaseApi.js
- components/formFields.js
- containers/Ideas/Idea.js
- containers/Ideas/IdeaCreate.js
- containers/Ideas/IdeaProject.js
- containers/Ideas/IdeasList.js
- containers/Ideas/IdeasListItem.js
Only works with https://github.com/liqd/adhocracy-plus/pull/1400
I couldnt check/do the image posting/editing, because the submit button is not reachable anymore when a picture is uploaded :shrug:  So this will have to wait for later.
I also added one issue that I could not fix so far https://github.com/liqd/zt-app/issues/101
> Ks 2021 08 edit ideas

- Makefile
- chrome.sh
Add a Makefile which makes it easier to clean the cache and run the app
> add Makefile with basic targets

- .eslintrc.json
- .github/workflows/react.yml
- .gitignore
- Makefile
- babel.config.js
- components/__tests__/Menu.test.js
- components/__tests__/MenuItem.test.js
- components/__tests__/__snapshots__/Menu.test.js.snap
- components/__tests__/__snapshots__/MenuItem.test.js.snap
- package.json
Add js testing framework and an initial test
> jd 2021 09 js testing

- babel.config.js
app/post-image: using dynamic uri and setting image filename
app/post-image: using dynamic mime type
app/image-post: remove passing unused ideas to ideaslistitem
app/ideas: fixing bugs with props.ideas & removing babel properties
> containers/ideas: post idea image to API with formData

- containers/Ideas/IdeasList.js
If we do not have the right Backend set, it will fail! This shows a message that helps maybe to set it.
> ideas/list: if wrong backend or no ideas fetched

- BaseApi.js
- Makefile
- app.config.js
- package.json
based on
* device (emulator/web/real)
* build type (PROD/DEV)
* environment variable LOCAL_API
> auto-select api url

- BaseApi.js
- containers/Comments/Comment.js
- containers/Comments/CommentForm.js
- containers/Comments/CommentForm.styles.js
- containers/Comments/Comments.js
- containers/Ideas/Idea.js
- docs/debugging.md
~~Only works with https://github.com/liqd/adhocracy-plus/pull/1676/ or once that is merged.~~ Aplus is already updated.
Styling of the comment form is still missing as well as making it sticky.
To do (probably in new PR):
> BaseApi//Comments: add CommentForm component and post comments

- components/LabelForm.js
- components/LabelForm.styles.js
- components/formFields.js
- components/formFields.styles.js
- components/imageFormField.js
- components/imageFormField.styles.js
- containers/Ideas/Idea.styles.js
- containers/Ideas/IdeaCreate.js
render cycle caused the form to be re-rendered and therefore user inputs got
vanished.
> ideas/ideaCreate: preventing re-rendering while interacting with form

- BaseApi.js
- containers/Comments/Comment.js
- containers/Comments/SubComment.js
- containers/Comments/SubComments.js
- containers/Ideas/Idea.js
So this is branched off of https://github.com/liqd/zt-app/pull/223 which needs to be merged first and then this needs rebase.
> Ks 2022 01 rate comments

- components/ButtonTextInput.js
- components/ButtonTextInput.styles.js
- components/formFields.js
- components/formFields.styles.js
- containers/Ideas/Idea.styles.js
- containers/Ideas/IdeaCreate.js
- containers/Ideas/IdeaCreateDescription.js
- navigation/IdeaNavigator.js
This is just the styling, no form submission - should not be merged yet
> [#5171] description textinput view

- BaseApi.js
- containers/Comments/Comment.js
- containers/Comments/Comments.js
- containers/Comments/SubComment.js
- containers/Comments/SubComments.js
- containers/Ideas/Idea.js
Styling of deleted comments is not ideal, but there is no design yet, so maybe lets wait what marcelo says?
> Ks 2022 01 delete comments

- BaseApi.js
- components/imageFormField.js
- components/imageFormField.styles.js
- containers/Comments/Comment.js
- containers/Ideas/Idea.js
- containers/Ideas/IdeaCreate.js
- containers/Ideas/IdeaCreateDescription.js
- containers/Ideas/IdeaProject.js
- containers/Ideas/IdeasListItem.js
Only works with https://github.com/liqd/adhocracy-plus/pull/1710
Last commit is cherry-picked from https://github.com/liqd/zt-app/pull/244, so fixes #251 and closes https://github.com/liqd/zt-app/pull/244
> Ks 2022 02 issues

- containers/Comments/Comment.js
- containers/Comments/SubComment.js
- containers/Ideas/ExploreListItem.js
- containers/Ideas/ExploreListItem.styles.js
@Rineee and here the corresponding aplus PR:
https://github.com/liqd/adhocracy-plus/pull/1955
> adding progressbar to ExploreListItem

- webpack.config.js
helps with checking dimensions, margin, etc.
> expo: make web version work again

- containers/Ideas/IdeaProject.js
- containers/Ideas/IdeaProject.styles.js
after previous attempts with tab libs was decided using buttons would be simpler
> [#6178] IdeaProject: make tab/buttons show correct content when clicked

- __mocks__/@react-native-async-storage/async-storage.js
- containers/Comments/Comment.js
- containers/Comments/SubComment.js
- containers/Comments/__tests__/Comment.test.js
- containers/Comments/__tests__/__snapshots__/Comment.test.js.snap
- containers/Ideas/__tests__/Idea.test.js
- containers/Ideas/__tests__/__snapshots__/Idea.test.js.snap
- tests/TestData.js
* fix some unncessary useStates
* add some tests for comments + ideas
> Jd 2022 07 comments test

- components/Richtext.js
- components/RichtextCollapsibleItem.js
- components/RichtextCollapsibleItem.styles.js
- components/__tests__/Richtext.test.js
- containers/Ideas/Idea.js
- containers/Ideas/Idea.styles.js
- containers/Ideas/IdeaProject.js
- containers/Ideas/IdeaProject.styles.js
- package.json
Note: needs backend to send `project.information` without striptags.
> richtext (ckeditor PoC)

- BaseApi.js
- components/ButtonTextInput.js
- components/ButtonTextInput.styles.js
- components/formFields.js
- components/formFields.styles.js
- containers/Comments/Comment.js
- containers/Comments/Comments.js
- containers/Ideas/Idea.js
- containers/Ideas/Idea.styles.js
- containers/Ideas/IdeaCreate.js
- containers/Ideas/IdeaCreateDescription.js
- containers/Ideas/IdeaProject.styles.js
- containers/Ideas/__tests__/__snapshots__/Idea.test.js.snap
- containers/Reports/ReportCreateMessage.js
- containers/Reports/ReportCreateMessage.styles.js
- navigation/IdeaNavigator.js
branched off of https://github.com/liqd/zt-app/pull/329 and continued working on this one, kind of by accident but felt it was bit late once I realised
> [#6146] report ideas and comments

- containers/Ideas/IdeaProject.js
- containers/Ideas/IdeaProject.styles.js
depending on https://github.com/liqd/adhocracy-plus/pull/1979
> containers/ideas: add contact info to project info tab

- containers/Ideas/ExplorePage.js
- containers/Ideas/IdeaProject.js
- containers/Ideas/IdeaProject.styles.js
- containers/Ideas/Phase.js
- containers/Ideas/Phase.styles.js
Needs https://github.com/liqd/adhocracy-plus/pull/1990
> Ks 2022 07 issues

- .eslintrc.json
- components/Header.js
- components/Header.styles.js
- components/__tests__/Header.test.js
- components/__tests__/__snapshots__/Header.test.js.snap
- containers/Ideas/Idea.js
- containers/Ideas/Idea.styles.js
- containers/Ideas/IdeaCreate.js
- containers/Ideas/IdeaCreate.styles.js
- containers/Ideas/IdeaCreateDescription.js
- containers/Ideas/IdeaProject.js
- containers/Ideas/__tests__/__snapshots__/Idea.test.js.snap
- containers/Reports/ReportCreateMessage.js
- containers/Reports/ReportCreateMessage.styles.js
fix the issue with the back button not being clickable if it's too close the the android status bar. Apparently I'm the only one having the issue though. This makes the position also more consistent with the Idealist view.
> add header component, make header look coherent on all pages

- BaseApi.js
- containers/Comments/Comment.js
- containers/Ideas/ExplorePage.js
- containers/Ideas/Idea.js
- containers/Ideas/IdeaProject.js
- containers/Ideas/__tests__/Idea.test.js
I changed the permissions in backend for project and module api, so only authenticated users are allowed. I guess that makes more sense, right? It is here: https://github.com/liqd/adhocracy-plus/pull/1993
That way we can now easily check on explore page if the token is valid and log out the user, if not. I copied a bit from @goapunk s former PR :)
And I broke the frontend tests, but have no idea how to fix that :see_no_evil: Maybe someone can do that or even pair with me on it? That would be great!
> logout if wrong token

- containers/Ideas/IdeaCreate.js
I think this works, but couldn't properly test it, because the API on dev responded too fast even when I added an image.
Not sure if that would confirm it enough, but maybe we could test with adding a "wait for 10 seconds" before sending the request? What would that be in js?
> containers/ideas: disable button after idea submit

- components/RichtextCollapsibleItem.js
- components/RichtextCollapsibleItem.styles.js
> RichtextCollapsibleItem: style collapsible title bigger and bold

- App.js
- containers/Ideas/Idea.js
- containers/Ideas/__tests__/__snapshots__/Idea.test.js.snap
- navigation/IdeaNavigator.js
> Jd 2022 07 auto focus on edit + enable swipe gestures on iOS

- containers/Ideas/IdeaCreate.js
needs https://github.com/liqd/adhocracy-plus/pull/2003
This hopefully fixes https://github.com/liqd/zt-app/issues/263 as it handles image deletion differently.
There was also a bug, that if an idea with an image was edited without editing the image, the image was deleted on submit :see_no_evil:
> Ideas/IdeaCreate: fix image sending errors

- containers/Comments/CommentForm.js
- containers/Comments/CommentForm.styles.js
- containers/Ideas/ExplorePage.js
- containers/Ideas/ExplorePage.styles.js
- containers/Ideas/Idea.js
- containers/Ideas/IdeaCreate.js
- containers/Ideas/IdeaCreate.styles.js
- containers/Ideas/IdeaProject.js
- containers/Ideas/__tests__/__snapshots__/Idea.test.js.snap
> CommentForm: adjusting styles to fix bug closes #265

- components/Header.js
- components/Header.styles.js
- components/__tests__/__snapshots__/Header.test.js.snap
- containers/Comments/CommentForm.styles.js
- containers/Ideas/ExplorePage.styles.js
- containers/Ideas/Idea.js
- containers/Ideas/Idea.styles.js
- containers/Ideas/IdeaCreate.styles.js
- containers/Ideas/IdeaProject.js
- containers/Ideas/__tests__/__snapshots__/Idea.test.js.snap
- containers/Reports/ReportCreateMessage.js
- containers/Reports/ReportCreateMessage.styles.js
> Jd 2022 08 fix header status bar

- containers/Comments/Comment.js
- containers/Comments/__tests__/__snapshots__/Comment.test.js.snap
- containers/Ideas/ExplorePage.js
- containers/Ideas/__tests__/__snapshots__/Idea.test.js.snap
- containers/User/ProfileScreen.js
- containers/User/SettingsOverview.js
- containers/User/SettingsProfile.js
- containers/User/__tests__/__snapshots__/ProfileScreen.test.js.snap
Depends on both
https://github.com/liqd/adhocracy4/pull/1176
https://github.com/liqd/adhocracy-plus/pull/2018
and they need to be merged first in that order!
To test, you only need to install the aplus branch as that has the a4 update hash already in it.
Quesions/things to do, but I would say a thing for later? So maybe we can put that in the hibernation docs..
> Ks 2022 08 comments and profile pic

- src/BaseApi.js
> api: use aplus-app for prod

- App.js
- i18next-scanner.config.js
- src/BaseApi.js
- src/containers/Auth/AuthProvider.js
- src/containers/Ideas/ExplorePage.js
- src/containers/User/ProfileScreen.js
- src/containers/User/__tests__/ProfileScreen.test.js
- src/hooks/AuthenticatedUser.js
- src/hooks/User.js
- src/i18n.js
- src/navigation/IdeaNavigator.js
* set language based on user setting
* use last-used language when logged out
* move some api calls into custom hooks
* store user in AuthenticationProvider
depends on https://github.com/liqd/adhocracy-plus/pull/2282
> [7152] make app language aware

- Makefile
Add publish commands, the prod channel will use the app a+
> [7167] Makefile: add publish commands for dev and prod

- src/containers/Ideas/ExplorePage.js
- src/navigation/IdeaNavigator.js
I changed it in another PR but realized that doesn't make much sense, so changing it back.
> router: switch back to token to check if logged in

- src/components/KeyboardScrollView.js
- src/components/StatusBarStyled.js
- src/components/TextSourceSans.js
- src/containers/Auth/LoginScreen.js
- src/containers/Ideas/ExplorePage.js
- src/containers/Ideas/Idea.js
- src/containers/Ideas/IdeaCreate.js
- src/containers/Ideas/IdeaCreateDescription.js
- src/containers/Ideas/IdeaProject.js
- src/containers/Reports/ReportCreateMessage.js
- src/containers/User/ProfileScreen.js
- src/containers/User/SettingsOverview.js
- src/containers/User/SettingsProfile.js
- src/containers/User/SettingsProfileAvatar.js
I tried things with the StatusBar for #399 but I have no idea if that is how we should do it? :grimacing: 
I did the ReactNative way: https://reactnative.dev/docs/statusbar 
but there is also an expo one: https://docs.expo.dev/guides/configuring-statusbar/
fixes #399
> components: add statusBar with styles
